FROM schematron:base AS base


FROM klakegg/saxon

RUN apk add --no-cache zip \
 && ln -s /bin/schxslt /bin/schematron

COPY --from=base /schxslt /
COPY --from=base /klakegg /

ENTRYPOINT ["schxslt"]
